# Generated by Django 2.0.6 on 2018-07-04 11:18

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('HP', 'Happiness Program'), ('AMP', 'Advance Meditation Program'), ('DSN', 'Dynamism For Self And Nation'), ('SSY2', 'Sri Sri Yoga Level 2'), ('SSY1', 'Sri Sri Yoga Level 1'), ('VTP', 'Volunteer Training Program'), ('HPY', 'Happiness Program for Youth'), ('YES+', 'Youth Empowerment and Skills Workshop'), ('MY', 'Medha Yoga'), ('PY', 'Pragna Yoga'), ('AE', 'Art Excel')], max_length=4)),
                ('start_date', models.DateTimeField(db_index=True)),
                ('end_date', models.DateTimeField()),
                ('admins', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), db_index=True, size=None)),
                ('volunteers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), db_index=True, size=None)),
                ('total_participants', models.IntegerField(default=0)),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
