# Generated by Django 2.0.6 on 2018-07-04 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='total_participants',
            new_name='total_leads',
        ),
    ]
