# Generated by Django 2.0.6 on 2018-07-04 17:05

import django.contrib.postgres.fields
import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.contrib.postgres.operations import CITextExtension


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180704_1121'),
    ]

    operations = [
        CITextExtension(),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', django.contrib.postgres.fields.citext.CIEmailField(max_length=100)),
                ('history', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.citext.CITextField(), size=None)),
                ('lead_status', models.CharField(choices=[('INTR', 'Interested'), ('PEND', 'Filled the form, payment pending'), ('PART', 'Part Payment'), ('NI', 'Not Interested'), ('NC', 'Next Course'), ('AOL', 'Already in AOL'), ('PAID', 'Paid'), ('DROP', 'Drop Out'), ('NOSO', 'No Show'), ('COMP', 'Completed')], default='INTR', max_length=3)),
                ('target_type', models.CharField(choices=[('HP', 'Happiness Program'), ('AMP', 'Advance Meditation Program'), ('DSN', 'Dynamism For Self And Nation'), ('SSY2', 'Sri Sri Yoga Level 2'), ('SSY1', 'Sri Sri Yoga Level 1'), ('VTP', 'Volunteer Training Program'), ('HPY', 'Happiness Program for Youth'), ('YES+', 'Youth Empowerment and Skills Workshop'), ('MY', 'Medha Yoga'), ('PY', 'Pragna Yoga'), ('AE', 'Art Excel')], default='HP', max_length=4)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='target',
            name='target_type',
            field=models.CharField(choices=[('HP', 'Happiness Program'), ('AMP', 'Advance Meditation Program'), ('DSN', 'Dynamism For Self And Nation'), ('SSY2', 'Sri Sri Yoga Level 2'), ('SSY1', 'Sri Sri Yoga Level 1'), ('VTP', 'Volunteer Training Program'), ('HPY', 'Happiness Program for Youth'), ('YES+', 'Youth Empowerment and Skills Workshop'), ('MY', 'Medha Yoga'), ('PY', 'Pragna Yoga'), ('AE', 'Art Excel')], default='HP', max_length=4),
        ),
        migrations.AddField(
            model_name='lead',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Target'),
        ),
    ]
